apiVersion: v1
kind: Pod
metadata:
 name: result-app-pod
 labels:
  name: result-app-pod
  app: demo-result-app
spec:
 conatiners:
  - name: result-app
    image: kodecloud/examplevotingapp_result:v1
    port: 
     -conatainerPort: 80