apiVersion: v1
kind: Pod
metadata:
 name: worker-app-pod
 labels:
  name: worker-app-pod
  app: demo-voting-app
spec:
 conatiners:
  - name: worker-app
    image: kodecloud/examplevotingapp_worker:v1